management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  server:
    name: service_one
  rabbitmq:
    username: rabbitmq
    password: rabbitmq

cvortex:
  message: Mensagem Gerada dentro do K8S - Atualização via Webhook Teste 2