server:
  port: 80

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  server:
    name: service_one-dev
  rabbitmq:
    host: rabbitmq.rabbitmq.svc.cluster.local
    port: 5672
    username: rabbitmq
    password: rabbitmq

cvortex:
  message: Mensagem Gerada dentro do K8S - Atualização via Webhook 12