server:
  port: 80

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  server:
    name: service-two-dev
  rabbitmq:
    host: rabbitmq.rabbitmq
    port: 5672
    username: rabbitmq
    password: rabbitmq

cvortex:
  message: Mensagem Gerada dentro do K8S Teste 2