server:
  port: 8082

spring:
  server:
    name: service-two-local
  data:
    mongodb:
      host: 192.168.0.104 
      port: 30017
      database: service-two
      authentication-database: admin
      password: 1234
      username: root
      repositories:
        enabled: true