server:
  port: 8082

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  server:
    name: service-two-local
  rabbitmq:
    host: 192.168.0.104
    port: 30072
    username: rabbitmq
    password: rabbitmq
  # data:
  #   mongodb:
  #     host: 192.168.0.104 
  #     port: 30017
  #     database: admin
  #     authentication-database: admin
  #     password: 1234
  #     username: root
  #     repositories:
  #       enabled: true

cvortex:
  message: Mensagem Inicial